# Generated by Django 4.2.9 on 2024-01-26 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("my_creations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("text", models.TextField()),
                (
                    "rate",
                    models.IntegerField(
                        choices=[
                            (2, "2"),
                            (5, "5"),
                            (3, "3"),
                            (4, "4"),
                            (0, "0"),
                            (1, "1"),
                        ]
                    ),
                ),
                (
                    "creation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_creations.creation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
